window.SUPABASE_URL = "https://xvaliytxekkpybfywetg.supabase.co";
window.SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2YWxpeXR4ZWtrcHliZnl3ZXRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODg4Mzk0MDMsImV4cCI6MjEwNDQxNTQwM30.7y3eeguZ5gcSrPcha6HVU2rVTvSeQIeMIwBZFqD8fkc";
